# Generated by Django 5.1.2 on 2024-10-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renforcementbackend', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
